### ISSUE TITLE
Pas d'affichage du joueur, ni du texte des statistiques

### ISSUE THREAD

**Issue by Qu3tzal** [Qu3tzal/meuporg#27]
Voir screenshot attaché.
Pas de message d'erreur, les fichiers d'assets sont bien là.
Tu peux me dire si tu as le même bug @om3g4zell ?

![screenshot-meuporg-client-royale](https://user-images.githubusercontent.com/4190526/41992523-fe1089b0-7a48-11e8-91bd-fa57f139143a.png)

**Comment by Qu3tzal** [comment]
Je rajoute le label 'server' parce que j'ai l'impression que le problème vient du fait qu'aucune entité n'est spawn.

**Comment by Qu3tzal** [comment]
Je ne crains que le commit 07af30e42e7ffa73efd6dcd7178716a3f956c496 ait cassé quelque chose du genre la gestion des id des entités.

**Comment by om3g4zell** [comment]
ça c'est quand notre attribut Player n'est pas set

**Comment by Qu3tzal** [comment]
J'ai revert le commit 07af30e42e7ffa73efd6dcd7178716a3f956c496 avec le commit b0f96abffe28a4029436d41714de5aa95ecef8d4. Plus de problème sur Ubuntu 16.04 64 bits.

**Comment by Qu3tzal** [comment]
Je retire l'issue de la milestone Royale v1 puisque c'est peut être à cause du passage forcé en sf::Uint64
