### ISSUE TITLE
Corriger le bug pour l'affichage du ping

### ISSUE THREAD

**Issue by om3g4zell** [Qu3tzal/meuporg#9]
Corriger le bug du ping pour avoir une statistique réseau importante en temps réel.

**Comment by Qu3tzal** [comment]
C'est quoi le bug du ping déjà ?

**Comment by om3g4zell** [comment]
bah ça marche pas ;)

**Comment by Qu3tzal** [comment]
Voir commit 6e19a3cce79399458cc99a05bb67fc7ca8017bd6
